export enum ModelName {
  POST = "Post",
  COMMENT = "Comment",
  USER = "User",
  SECTION = "Section",
  MESSAGE = "Message",
  CHAT_SESSION = "ChatSession",
  REMINDER = "Reminder",
  NOTIFICATION = "Notification",
  REPORT_TICKET = "ReportTicket",
  EVENT = "Event",
  FRIEND_REQUEST = "FriendRequest",
  FRIENDSHIP = "Friendship",
  GROUP = "Group",
}
